x-stoplight:
  docs:
    showModels: false

x-internal: true

openapi: 3.1.0
info:
  title: Playback Configuration API
  version: "1.0"
  contact:
    name: Jonathon Robins
    email: Jonathon.Robins@pamediagroup.com
  summary: Service used to manage playback service client configurations.
  description: |-
    Configuration API exposes the functionality to retrieve, update and delete playback client configurations. Also, 
    we can manage playback API key configuration using this API.
servers:
  - url: "https://api.playback.streamamg.com/v1/"
paths:
  /configuration/{configurationId}:
    get:
      tags:
      - Playback Configuration
      summary: Get playback configuration for a client
      parameters:
        - name: configurationId
          in: path
          description: Identifier of the client to retrieve the configuration for
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlaybackConfig"
    delete:
      tags:
      - Playback Configuration
      summary: Delete playback configuration for a client
      parameters:
        - name: configurationId
          in: path
          description: Identifier of the client to delete the configuration for
          required: true
          schema:
            type: string
      responses:
        "204":
          description: No Content
  /configuration:
    post:
      tags:
      - Playback Configuration
      summary: Create new playback configuration for a client
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PlaybackConfig"
      responses:
        "201":
          description: Created
          headers:
            Location:
              schema:
                type: string
    put:
      tags:
      - Playback Configuration
      summary: Update the playback configuration for a client
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PlaybackConfig"
      responses:
        "200":
          description: OK
  /configuration/{configurationId}/apikey:
    get:
      tags:
      - API Key Configuration
      summary: Get playback API key configuration for a client
      parameters:
        - name: configurationId
          in: path
          description: Identifier of the client to retrieve API key configuration for
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlaybackApiKeyConfig"
    post:
      tags:
      - API Key Configuration
      summary: Create new playback API key configuration for a client
      parameters:
        - name: configurationId
          in: path
          description: Identifier of the client to create API key configuration for
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PlaybackApiKeyConfig"
      responses:
        "201":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlaybackApiKeyConfig"
    delete:
      tags:
      - API Key Configuration
      summary: Delete playback api-key configuration for a client
      parameters:
        - name: configurationId
          in: path
          description: Identifier of the client to delete api-key configuration for
          required: true
          schema:
            type: string
      responses:
        "204":
          description: No Content
  /player:
    get:
      tags:
      - Player Configuration
      summary: Get player information
      description: Returns information about the player associated with the provided API key.
      parameters:
        - name: x-api-key
          in: header
          description: The API key to use for authentication.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Player"
components:
  schemas:
    PlaybackKeys:
      type: object
      properties:
        clientId:
          type: string
          example: "12345678-1111-1111-1111-123456789012"
      required:
        - configurationId

    Auth:
      type: object
      properties:
        cloudpay:
          type: object
          additionalProperties:
            type: string
          example:
            site: "some-site"
        engine:
          type: string
      required:
        - engine

    PlaybackConfig:
      allOf:
        - $ref: "#/components/schemas/PlaybackKeys"
        - type: object
          properties:
            auth:
              $ref: "#/components/schemas/Auth"
            domains:
              type: array
              items:
                type: string
                example: ["some-host1.com", "some-host2.com"]
            entitlementsUrl:
              type: string
            platform:
              type: object
              additionalProperties:
                type: object
              example:
                kaltura:
                  partnerId: "1234567"
            player:
              type: object
              additionalProperties:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    type: object
                    additionalProperties:
                      type: object
              example:
                configuration:
                  bitmovin:
                    "type": "bitmovin"
                    license: "12345678-1111-1111-1111-123456789012"
                    integrations:
                      mux:
                        env_key: "env_key_123"
                default: "bitmovin"
    PlaybackApiKeyConfig:
      allOf:
        - $ref: "#/components/schemas/PlaybackKeys"
        - type: object
          properties:
            apiKeyHash:
              type: string
              example: "some-apiKeyHash"
            apiKeyUuid:
              type: string
              example: "12345678-1111-1111-1111-123456789012"

    Player:
      allOf:
        - type: object
          properties:
            configuration:
              type: object
              additionalProperties:
                type: object
                properties:
                  "type":
                    type: string
                  license:
                    type: string
                  integrations:
                    type: object
                    additionalProperties:
                      type: object
                      additionalProperties:
                        type: string
                required:
                  - "type"
                  - license
              minProperties: 1
              example:
                "bitmovin":
                  "type": "bitmovin"
                  license: "12345678-1111-1111-1111-123456789012"
                  integrations:
                    mux:
                      env_key: "env_key_123"
            default:
              type: string
              example: "bitmovin"
      required:
        - configuration
        - default
